### ISSUE TITLE
issues with installing

### ISSUE THREAD

**Issue by tylerdurden6091** [ScrapeWithYuri/Live-Sports-Arbitrage-Bet-Finder#6]
python test1.py
Traceback (most recent call last):
  File "/home/james/Downloads/Live-Sports-Arbitrage-Bet-Finder-main/test1.py", line 535, in <module>
    app = App()
  File "/home/james/Downloads/Live-Sports-Arbitrage-Bet-Finder-main/test1.py", line 64, in __init__
    self.ask.driver.implicitly_wait(5)
AttributeError: 'ArbFinder' object has no attribute 'driver'

**Comment by personal-coding** [comment]
Please see [this solved issue](https://github.com/ScrapeWithYuri/Live-Sports-Arbitrage-Bet-Finder/issues/5) for more information. I've now added instructions in the readme as well.
